-- BASIC - FLAT
INSERT INTO
    "PropCare".subscriptions_plans (
        sub_id,
        sub_type,
        category,
        services,
        durations,
        rental_percentages,
        comments,
        created_by,
        is_active,
        created_at,
        updated_at
    )
VALUES (
        'VPC_SUB_001',
        'BASIC',
        'FLAT',
        ARRAY[
            'Rental services',
            'Tenant management',
            'Agreement with tenant and rental collection',
            'Tenant verification',
            'Vacating the tenant (pre-in, post)',
            'Quarterly physical inspections',
            'Preliminary report'
        ],
        '{"3": 3999, "6": 6499, "12": 10999}'::jsonb,
        '{"3": 7, "6": 7, "12": 7}'::jsonb,
        'Basic plan covering essential flat management and tenant coordination.',
        'admin_001',
        TRUE,
        NOW(),
        NOW()
    );

-- GOLD - FLAT
INSERT INTO
    "PropCare".subscriptions_plans (
        sub_id,
        sub_type,
        category,
        services,
        durations,
        rental_percentages,
        comments,
        created_by,
        is_active,
        created_at,
        updated_at
    )
VALUES (
        'VPC_SUB_002',
        'GOLD',
        'FLAT',
        ARRAY[
            'Rental services',
            'Tenant management',
            'Agreement with tenant and rental collection',
            'Tenant verification',
            'Vacating the tenant (pre-in, post)',
            'Quarterly physical inspections',
            'Preliminary report',
            'Quarterly walkthrough',
            'Utility and maintenance coordination',
            'Dedicated property manager'
        ],
        '{"3": 4999, "6": 7999, "12": 12999}'::jsonb,
        '{"3": 9, "6": 9, "12": 9}'::jsonb,
        'Gold plan with extended tenant and maintenance management features.',
        'admin_001',
        TRUE,
        NOW(),
        NOW()
    );

-- PLATINUM - FLAT
INSERT INTO
    "PropCare".subscriptions_plans (
        sub_id,
        sub_type,
        category,
        services,
        durations,
        rental_percentages,
        comments,
        created_by,
        is_active,
        created_at,
        updated_at
    )
VALUES (
        'VPC_SUB_003',
        'PLATINUM',
        'FLAT',
        ARRAY[
            'Encumbrance Certificate',
            'Physical verification',
            'Preliminary report',
            '15 days photos',
            'Monthly videos',
            'Agreements & lease',
            'Realtime updates',
            'Cost feasibility and analysis report',
            'Priority support',
            'Dedicated property manager',
            'Asset upkeep (cleaning, maintenance)',
            'Analysis & revenue on property'
        ],
        '{"3": "Custom Quote", "6": "Custom Quote", "12": "Custom Quote"}'::jsonb,
        '{"3": "Custom Quote", "6": "Custom Quote", "12": "Custom Quote"}'::jsonb,
        'Platinum plan — full-scale property management with upkeep, dedicated manager, and revenue analysis.',
        'admin_001',
        TRUE,
        NOW(),
        NOW()
    );

-- BASIC - PLOT
INSERT INTO
    "PropCare".subscriptions_plans (
        sub_id,
        sub_type,
        category,
        services,
        durations,
        rental_percentages,
        comments,
        created_by,
        is_active,
        created_at,
        updated_at
    )
VALUES (
        'VPC_SUB_004',
        'BASIC',
        'PLOT',
        ARRAY[
            'Monthly Photos',
            'Encumbrance Certificate',
            'Physical verification',
            'Preliminary report',
            'Bi-monthly videos'
        ],
        '{"3": 3999, "6": 6499, "12": 10999}'::jsonb,
        '{"3": 25, "6": 25, "12": 25}'::jsonb,
        'Basic plot management package with regular visual updates and verifications.',
        'admin_001',
        TRUE,
        NOW(),
        NOW()
    );

-- GOLD - PLOT
INSERT INTO
    "PropCare".subscriptions_plans (
        sub_id,
        sub_type,
        category,
        services,
        durations,
        rental_percentages,
        comments,
        created_by,
        is_active,
        created_at,
        updated_at
    )
VALUES (
        'VPC_SUB_005',
        'GOLD',
        'PLOT',
        ARRAY[
            'Encumbrance Certificate',
            '15 days photos',
            'Physical verification',
            'Preliminary report',
            'Monthly videos',
            'Agreements & lease',
            'Realtime updates',
            'Cost feasibility and analysis report',
            'Priority support'
        ],
        '{"3": 4999, "6": 7999, "12": 12999}'::jsonb,
        '{"3": 25, "6": 25, "12": 25}'::jsonb,
        'Gold package — detailed plot management with agreements and real-time updates.',
        'admin_001',
        TRUE,
        NOW(),
        NOW()
    );

-- PLATINUM - PLOT
INSERT INTO
    "PropCare".subscriptions_plans (
        sub_id,
        sub_type,
        category,
        services,
        durations,
        rental_percentages,
        comments,
        created_by,
        is_active,
        created_at,
        updated_at
    )
VALUES (
        'VPC_SUB_006',
        'PLATINUM',
        'PLOT',
        ARRAY[
            'Encumbrance Certificate',
            '15 days photos',
            'Physical verification',
            'Preliminary report',
            'Monthly videos',
            'Agreements & lease',
            'Realtime updates',
            'Cost feasibility and analysis report',
            'Priority support',
            'Dedicated property manager',
            'Asset upkeep (cleaning, maintenance)',
            'Analysis & revenue on property'
        ],
        '{"3": "Custom Quote", "6": "Custom Quote", "12": "Custom Quote"}'::jsonb,
        '{"3": "Custom Quote", "6": "Custom Quote", "12": "Custom Quote"}'::jsonb,
        'Platinum package — complete property lifecycle management with dedicated manager and analysis.',
        'admin_001',
        TRUE,
        NOW(),
        NOW()
    );

python - m celery - A background_task.celery_app.celery_app worker --loglevel=info

INSERT INTO
    property_details (
        user_id,
        property_id,
        property_name,
        survey_number,
        plot_number,
        house_number,
        project_name_or_venture,
        street,
        city,
        state,
        district,
        mandal,
        country,
        pin_code,
        size,
        sub_type,
        scale,
        rental_income,
        alternate_name,
        alternate_contact,
        land_mark,
        latitude,
        longitude,
        gmap_url,
        facing,
        type,
        admin_id,
        description,
        active_sub,
        associates_id,
        is_verified
    )
VALUES (
        'VPCUSR0101',
        'VPCPROP001',
        'Sunset Villa',
        NULL,
        '101',
        '10-1',
        'Green Valley',
        'Maple Street',
        'Hyderabad',
        'Telangana',
        'Medak',
        'Kulcharam',
        'India',
        500061,
        1200,
        'COMMERCIAL',
        'Sq. Feet',
        50000.00,
        'Ramesh',
        '9000000001',
        'Near Park',
        NULL,
        NULL,
        NULL,
        'North',
        'FLAT',
        NULL,
        'Sample property',
        false,
        NULL,
        true
    ),
    (
        'VPCUSR0101',
        'VPCPROP002',
        'Sunset Villa',
        NULL,
        '102',
        '10-2',
        'Green Valley',
        'Maple Street',
        'Hyderabad',
        'Telangana',
        'Medak',
        'Kulcharam',
        'India',
        500061,
        1250,
        'COMMERCIAL',
        'Sq. Feet',
        52000.00,
        'Ramesh',
        '9000000002',
        'Near Park',
        NULL,
        NULL,
        NULL,
        'East',
        'FLAT',
        NULL,
        'Sample property',
        false,
        NULL,
        true
    ),
    (
        'VPCUSR0101',
        'VPCPROP003',
        'Sunset Villa',
        NULL,
        '103',
        '10-3',
        'Green Valley',
        'Maple Street',
        'Hyderabad',
        'Telangana',
        'Medak',
        'Kulcharam',
        'India',
        500061,
        1180,
        'COMMERCIAL',
        'Sq. Feet',
        48000.00,
        'Ramesh',
        '9000000003',
        'Near Park',
        NULL,
        NULL,
        NULL,
        'West',
        'FLAT',
        NULL,
        'Sample property',
        false,
        NULL,
        false
    ),
    (
        'VPCUSR0101',
        'VPCPROP004',
        'Sunset Villa',
        NULL,
        '104',
        '10-4',
        'Green Valley',
        'Maple Street',
        'Hyderabad',
        'Telangana',
        'Medak',
        'Kulcharam',
        'India',
        500061,
        1300,
        'COMMERCIAL',
        'Sq. Feet',
        55000.00,
        'Ramesh',
        '9000000004',
        'Near Park',
        NULL,
        NULL,
        NULL,
        'South',
        'FLAT',
        NULL,
        'Sample property',
        false,
        NULL,
        true
    ),
    (
        'VPCUSR0101',
        'VPCPROP005',
        'Sunset Villa',
        NULL,
        '105',
        '10-5',
        'Green Valley',
        'Maple Street',
        'Hyderabad',
        'Telangana',
        'Medak',
        'Kulcharam',
        'India',
        500061,
        1350,
        'COMMERCIAL',
        'Sq. Feet',
        60000.00,
        'Ramesh',
        '9000000005',
        'Near Park',
        NULL,
        NULL,
        NULL,
        'North-East',
        'FLAT',
        NULL,
        'Sample property',
        false,
        NULL,
        true
    ),
    (
        'VPCUSR0101',
        'VPCPROP006',
        'Green Plot',
        NULL,
        '201',
        '11-1',
        'Palm Residency',
        'Palm Road',
        'Hyderabad',
        'Telangana',
        'Medak',
        'Kulcharam',
        'India',
        500062,
        240,
        'RESIDENTIAL',
        'Sq. Yards',
        NULL,
        'Suresh',
        '9000000006',
        'Near School',
        NULL,
        NULL,
        NULL,
        'North',
        'PLOT',
        NULL,
        'Open plot',
        false,
        NULL,
        false
    ),
    (
        'VPCUSR0101',
        'VPCPROP007',
        'Green Plot',
        NULL,
        '202',
        '11-2',
        'Palm Residency',
        'Palm Road',
        'Hyderabad',
        'Telangana',
        'Medak',
        'Kulcharam',
        'India',
        500062,
        260,
        'RESIDENTIAL',
        'Sq. Yards',
        NULL,
        'Suresh',
        '9000000007',
        'Near School',
        NULL,
        NULL,
        NULL,
        'East',
        'PLOT',
        NULL,
        'Open plot',
        false,
        NULL,
        true
    ),
    (
        'VPCUSR0101',
        'VPCPROP008',
        'Green Plot',
        NULL,
        '203',
        '11-3',
        'Palm Residency',
        'Palm Road',
        'Hyderabad',
        'Telangana',
        'Medak',
        'Kulcharam',
        'India',
        500062,
        280,
        'RESIDENTIAL',
        'Sq. Yards',
        NULL,
        'Suresh',
        '9000000008',
        'Near School',
        NULL,
        NULL,
        NULL,
        'West',
        'PLOT',
        NULL,
        'Open plot',
        false,
        NULL,
        false
    ),
    (
        'VPCUSR0101',
        'VPCPROP009',
        'Green Plot',
        NULL,
        '204',
        '11-4',
        'Palm Residency',
        'Palm Road',
        'Hyderabad',
        'Telangana',
        'Medak',
        'Kulcharam',
        'India',
        500062,
        300,
        'RESIDENTIAL',
        'Sq. Yards',
        NULL,
        'Suresh',
        '9000000009',
        'Near School',
        NULL,
        NULL,
        NULL,
        'South',
        'PLOT',
        NULL,
        'Open plot',
        false,
        NULL,
        true
    ),
    (
        'VPCUSR0101',
        'VPCPROP010',
        'Green Plot',
        NULL,
        '205',
        '11-5',
        'Palm Residency',
        'Palm Road',
        'Hyderabad',
        'Telangana',
        'Medak',
        'Kulcharam',
        'India',
        500062,
        320,
        'RESIDENTIAL',
        'Sq. Yards',
        NULL,
        'Suresh',
        '9000000010',
        'Near School',
        NULL,
        NULL,
        NULL,
        'North-East',
        'PLOT',
        NULL,
        'Open plot',
        false,
        NULL,
        true
    ),
    (
        'VPCUSR0101',
        'VPCPROP011',
        'Skyline Flat',
        NULL,
        '301',
        '12-1',
        'Skyline Towers',
        'Oak Street',
        'Hyderabad',
        'Telangana',
        'Medak',
        'Kulcharam',
        'India',
        500063,
        1500,
        'RESIDENTIAL',
        'Sq. Feet',
        70000.00,
        'Anil',
        '9000000011',
        'Near Mall',
        NULL,
        NULL,
        NULL,
        'North',
        'FLAT',
        NULL,
        'High-rise flat',
        true,
        NULL,
        true
    ),
    (
        'VPCUSR0101',
        'VPCPROP012',
        'Skyline Flat',
        NULL,
        '302',
        '12-2',
        'Skyline Towers',
        'Oak Street',
        'Hyderabad',
        'Telangana',
        'Medak',
        'Kulcharam',
        'India',
        500063,
        1550,
        'RESIDENTIAL',
        'Sq. Feet',
        72000.00,
        'Anil',
        '9000000012',
        'Near Mall',
        NULL,
        NULL,
        NULL,
        'East',
        'FLAT',
        NULL,
        'High-rise flat',
        true,
        NULL,
        true
    ),
    (
        'VPCUSR0101',
        'VPCPROP013',
        'Skyline Flat',
        NULL,
        '303',
        '12-3',
        'Skyline Towers',
        'Oak Street',
        'Hyderabad',
        'Telangana',
        'Medak',
        'Kulcharam',
        'India',
        500063,
        1480,
        'RESIDENTIAL',
        'Sq. Feet',
        68000.00,
        'Anil',
        '9000000013',
        'Near Mall',
        NULL,
        NULL,
        NULL,
        'West',
        'FLAT',
        NULL,
        'High-rise flat',
        true,
        NULL,
        false
    ),
    (
        'VPCUSR0101',
        'VPCPROP014',
        'Skyline Flat',
        NULL,
        '304',
        '12-4',
        'Skyline Towers',
        'Oak Street',
        'Hyderabad',
        'Telangana',
        'Medak',
        'Kulcharam',
        'India',
        500063,
        1600,
        'RESIDENTIAL',
        'Sq. Feet',
        75000.00,
        'Anil',
        '9000000014',
        'Near Mall',
        NULL,
        NULL,
        NULL,
        'South',
        'FLAT',
        NULL,
        'High-rise flat',
        true,
        NULL,
        true
    ),
    (
        'VPCUSR0101',
        'VPCPROP015',
        'Skyline Flat',
        NULL,
        '305',
        '12-5',
        'Skyline Towers',
        'Oak Street',
        'Hyderabad',
        'Telangana',
        'Medak',
        'Kulcharam',
        'India',
        500063,
        1650,
        'RESIDENTIAL',
        'Sq. Feet',
        77000.00,
        'Anil',
        '9000000015',
        'Near Mall',
        NULL,
        NULL,
        NULL,
        'North-East',
        'FLAT',
        NULL,
        'High-rise flat',
        true,
        NULL,
        true
    ),
    (
        'VPCUSR0102',
        'VPCPROP016',
        'Lake View Villa',
        NULL,
        '401',
        '20-1',
        'Lake View',
        'Lake Road',
        'Hyderabad',
        'Telangana',
        'Ranga Reddy',
        'Shamshabad',
        'India',
        501218,
        1800,
        'RESIDENTIAL',
        'Sq. Feet',
        85000.00,
        'Kiran',
        '9000000016',
        'Near Lake',
        NULL,
        NULL,
        NULL,
        'North',
        'VILLA',
        NULL,
        'Luxury villa',
        true,
        NULL,
        true
    ),
    (
        'VPCUSR0102',
        'VPCPROP017',
        'Lake View Villa',
        NULL,
        '402',
        '20-2',
        'Lake View',
        'Lake Road',
        'Hyderabad',
        'Telangana',
        'Ranga Reddy',
        'Shamshabad',
        'India',
        501218,
        1850,
        'RESIDENTIAL',
        'Sq. Feet',
        88000.00,
        'Kiran',
        '9000000017',
        'Near Lake',
        NULL,
        NULL,
        NULL,
        'East',
        'VILLA',
        NULL,
        'Luxury villa',
        true,
        NULL,
        true
    ),
    (
        'VPCUSR0102',
        'VPCPROP018',
        'Lake View Villa',
        NULL,
        '403',
        '20-3',
        'Lake View',
        'Lake Road',
        'Hyderabad',
        'Telangana',
        'Ranga Reddy',
        'Shamshabad',
        'India',
        501218,
        1750,
        'RESIDENTIAL',
        'Sq. Feet',
        83000.00,
        'Kiran',
        '9000000018',
        'Near Lake',
        NULL,
        NULL,
        NULL,
        'West',
        'VILLA',
        NULL,
        'Luxury villa',
        true,
        NULL,
        false
    ),
    (
        'VPCUSR0102',
        'VPCPROP019',
        'Lake View Villa',
        NULL,
        '404',
        '20-4',
        'Lake View',
        'Lake Road',
        'Hyderabad',
        'Telangana',
        'Ranga Reddy',
        'Shamshabad',
        'India',
        501218,
        1900,
        'RESIDENTIAL',
        'Sq. Feet',
        90000.00,
        'Kiran',
        '9000000019',
        'Near Lake',
        NULL,
        NULL,
        NULL,
        'South',
        'VILLA',
        NULL,
        'Luxury villa',
        true,
        NULL,
        true
    ),
    (
        'VPCUSR0102',
        'VPCPROP020',
        'Lake View Villa',
        NULL,
        '405',
        '20-5',
        'Lake View',
        'Lake Road',
        'Hyderabad',
        'Telangana',
        'Ranga Reddy',
        'Shamshabad',
        'India',
        501218,
        1950,
        'RESIDENTIAL',
        'Sq. Feet',
        92000.00,
        'Kiran',
        '9000000020',
        'Near Lake',
        NULL,
        NULL,
        NULL,
        'North-East',
        'VILLA',
        NULL,
        'Luxury villa',
        true,
        NULL,
        true
    );